spin_manifest_version = 2

[application]
authors = ["{{authors}}"]
description = "{{project-description}}"
name = "{{project-name}}"
version = "0.1.0"

[[trigger.http]]
route = "{{http-path}}"
component = "{{project-name | kebab_case}}"

[component.{{project-name | kebab_case}}]
source = "app.wasm"
[component.{{project-name | kebab_case}}.build]
command = "spin py2wasm app -o app.wasm"
watch = ["app.py", "Pipfile"]
