spin_version = "1"
authors = ["Fermyon Engineering <engineering@fermyon.com>"]
description = "Spin Python SDK example"
name = "python-sdk-example"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "python-sdk-example"
environment = { hello = "teapot" }
config = { redis_address = "redis://127.0.0.1:6379" }
files = [{ source = "static-assets/", destination = "/" }]
source = "app.wasm"
allowed_http_hosts = ["insecure:allow-all"]
[component.trigger]
route = "/..."
[component.build]
command = "../../target/release/spin-python app -o app.wasm"
