spin_manifest_version = 2

[application]
authors = ["Fermyon Engineering <engineering@fermyon.com>"]
description = "Spin Python SDK hello world"
name = "spin-py-hello-world"
version = "0.1.0"

[[trigger.http]]
route = "/..."
component = "python-sdk-example"

[component.python-sdk-example]
source = "app.wasm"
[component.python-sdk-example.build]
command = "spin py2wasm app -o app.wasm"
watch = ["app.py"]
