spin_manifest_version = 2

[application]
authors = ["Fermyon Engineering <engineering@fermyon.com>"]
description = "Spin Python SDK sqlite example"
name = "spin-py-sqlite"
version = "0.1.0"

[[trigger.http]]
route = "/..."
component = "py-sqlite"

[component.py-sqlite]
source = "app.wasm"
sqlite_databases = ["default"]
[component.py-sqlite.build]
command = "spin py2wasm app -o app.wasm"
watch = ["app.py"]
