spin_manifest_version = 2

[application]
authors = ["Fermyon Engineering <engineering@fermyon.com>"]
description = "Spin Python SDK hello llm"
name = "spin-py-hello-llm"
version = "0.1.0"

[[trigger.http]]
route = "/..."
component = "py-hello-llm"

[component.py-hello-llm]
source = "app.wasm"
ai_models = ["llama2-chat", "all-minilm-l6-v2"]
[component.py-hello-llm.build]
command = "spin py2wasm app -o app.wasm"
watch = ["app.py"]
