spin_manifest_version = 2

[application]
name = "test"
version = "0.1.0"
authors = ["Fermyon Engineering <engineering@fermyon.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "test"

[component.test]
source = "app.wasm"
allowed_outbound_hosts = []
key_value_stores = ["default"]
[component.test.build]
command = "componentize-py -w spin-http componentize app -o app.wasm"
