spin_manifest_version = 2

[application]
authors = ["Fermyon Engineering <engineering@fermyon.com>"]
description = "Spin Python SDK KV"
name = "spin-py-kv"
version = "0.1.0"

[[trigger.http]]
route = "/..."
component = "py-kv"

[component.py-kv]
source = "app.wasm"
key_value_stores = ["default"]
[component.py-kv.build]
command = "spin py2wasm app -o app.wasm"
watch = ["app.py"]
