spin_manifest_version = 2

[application]
authors = ["Fermyon Engineering <engineering@fermyon.com>"]
description = "Spin Python Outbound HTTP Example"
name = "Spin-python-outbound-http"
version = "0.1.0"

[[trigger.http]]
route = "/..."
component = "python-outbound-http"

[component.python-outbound-http]
source = "app.wasm"
environment = { hello = "teapot" }
allowed_http_hosts = ["random-data-api.fermyon.app"]
[component.python-outbound-http.build]
command = "spin py2wasm app -o app.wasm"
watch = ["app.py"]
